-- Sons de base inclus avec l’addon
SoundBoard_Sounds = {
    ["ding"] = "Interface\\AddOns\\SoundBoard\\Sounds\\ding.ogg",
    ["wouah"] = "Interface\\AddOns\\SoundBoard\\Sounds\\wow.ogg",
    ["buzzer"] = "Interface\\AddOns\\SoundBoard\\Sounds\\buzzer.ogg",
    ["fart"] = "Interface\\AddOns\\SoundBoard\\Sounds\\fart.ogg",
    ["quack"] = "Interface\\AddOns\\SoundBoard\\Sounds\\coin.ogg",
    ["laugh"] = "Interface\\AddOns\\SoundBoard\\Sounds\\mouhahaha.ogg",
    ["claps"] = "Interface\\AddOns\\SoundBoard\\Sounds\\claps.mp3",
    ["alerte"] = "Interface\\AddOns\\SoundBoard\\Sounds\\alerte.mp3",
    ["sheep"] = "Interface\\AddOns\\SoundBoard\\Sounds\\sheep.mp3",
    ["cat"] = "Interface\\AddOns\\SoundBoard\\Sounds\\cat.mp3",
    ["game-over"] = "Interface\\AddOns\\SoundBoard\\Sounds\\game-over.mp3",
    ["fail"] = "Interface\\AddOns\\SoundBoard\\Sounds\\fail.mp3",
    ["running"] = "Interface\\AddOns\\SoundBoard\\Sounds\\running.mp3",
    ["yeah-boy"] = "Interface\\AddOns\\SoundBoard\\Sounds\\yeah-boy.mp3",
    ["huh"] = "Interface\\AddOns\\SoundBoard\\Sounds\\huh.mp3",
    ["putri"] = "Interface\\AddOns\\SoundBoard\\Sounds\\putri.mp3",
    ["cow"] = "Interface\\AddOns\\SoundBoard\\Sounds\\cow.mp3",
    ["error"] = "Interface\\AddOns\\SoundBoard\\Sounds\\error.mp3",
    ["minion"] = "Interface\\AddOns\\SoundBoard\\Sounds\\minion.mp3",
    ["war"] = "Interface\\AddOns\\SoundBoard\\Sounds\\war.mp3",
    ["lets-go"] = "Interface\\AddOns\\SoundBoard\\Sounds\\lets-go.mp3",
    ["whip"] = "Interface\\AddOns\\SoundBoard\\Sounds\\whip.mp3",
 }